In [47]:
import pandas as pd
import numpy as np

df = pd.read_excel("scores.xlsx")
df

    班级    姓名         学号   语文   数学    英语  物理   化学   生物
0    1   贾婧瑜  202460101  109  126  81.5  55   93   96
1    1   李东泽  202460102  118  113  51.0  63   96   98
2    1   王子涵  202460104  105   73  51.0  61   99  100
3    1   张乘瑞  202460111   88  107  38.0  57  100   91
4    1   任玉莹  202460106  103   86  75.0  46   89   85
..  ..   ...        ...  ...  ...   ...  ..  ...  ...
72   3   黄琬婷  202440217   87   34  40.5  33   58   42
73   3   宋鑫淼  202440313   88   20  33.0  16   48   56
74   3   杨皓鑫  202440307   69   34  37.5  14   48   58
75   3   刘昌林  202440318   15   19  42.0  10   58   41
76   3  董吴议泽  202440317    0    0  27.0   0   30   48

[77 rows x 9 columns]

In [37]:
# 1班语文平均成绩
print(df[df["班级"] == 1]["语文"].mean())
# 1班语文平均成绩，不包含0分
print(df[(df["班级"] == 1) & (df["语文"] != 0)]["语文"].mean())
# 计算总成绩，增加到最后一列
df["总成绩"] = df["语文"] + df["数学"] + df["英语"] + df["物理"] + df["化学"] + df["生物"]

94.75
98.25925925925925

In [22]:
# 数据预处理
# 将各科成绩中的0替换为NaN（表示无效值），确保计算平均值时自动忽略这些数据：
score_columns = ['语文', '数学', '英语', '物理', '化学', '生物']
df[score_columns] = df[score_columns].replace(0, np.nan)
df

    班级    姓名         学号     语文     数学    英语    物理     化学     生物
0    1   贾婧瑜  202460101  109.0  126.0  81.5  55.0   93.0   96.0
1    1   李东泽  202460102  118.0  113.0  51.0  63.0   96.0   98.0
2    1   王子涵  202460104  105.0   73.0  51.0  61.0   99.0  100.0
3    1   张乘瑞  202460111   88.0  107.0  38.0  57.0  100.0   91.0
4    1   任玉莹  202460106  103.0   86.0  75.0  46.0   89.0   85.0
..  ..   ...        ...    ...    ...   ...   ...    ...    ...
72   3   黄琬婷  202440217   87.0   34.0  40.5  33.0   58.0   42.0
73   3   宋鑫淼  202440313   88.0   20.0  33.0  16.0   48.0   56.0
74   3   杨皓鑫  202440307   69.0   34.0  37.5  14.0   48.0   58.0
75   3   刘昌林  202440318   15.0   19.0  42.0  10.0   58.0   41.0
76   3  董吴议泽  202440317    NaN    NaN  27.0   NaN   30.0   48.0

[77 rows x 9 columns]

In [52]:
# 生成透视表
# 使用pivot_table按班级分组，计算各科平均分：
# pivot_table = df.pivot_table(index='班级', values=score_columns, aggfunc='mean').round(2)  # 保留两位小数
# 将pivot_table保存到Excel文件：
# pivot_table.to_excel('pivot_table.xlsx')
# pivot_table
score_columns = ['语文', '数学', '英语', '物理', '化学', '生物']
pd.pivot_table(df, index='班级', values=score_columns, aggfunc='mean').round(2)

       化学     数学     物理     生物     英语     语文
班级
1   83.18  66.29  37.68  81.36  55.79  94.75
2   61.31  38.52  24.62  67.59  40.83  79.86
3   58.65  48.05  24.55  66.05  47.72  73.00

In [53]:
import pandas as pd

# 示例数据
data = {'地区': ['北京', '上海', '北京', '上海', '北京'], '产品类别': ['A', 'B', 'A', 'B', 'A'], '销售额': [200, 150, 300, 250, 400], '利润': [50, 30, 70, 40, 90]}
df = pd.DataFrame(data)

# 创建透视表：按地区和产品类别分组，计算销售额总和与利润均值，填充缺失值为0
pivot_table = pd.pivot_table(df, values=['销售额', '利润'], index='地区', columns='产品类别',
 aggfunc={'销售额': 'sum', '利润': 'mean'}, fill_value=0, margins=True)
pivot_table

      利润            销售额
产品类别   A   B   All    A    B   All
地区
上海     0  35  35.0    0  400   400
北京    70   0  70.0  900    0   900
All   70  35  56.0  900  400  1300

In [ ]:
pd.pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False)