In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])
print(df)

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [9]:
df = pd.read_csv('data.csv', encoding='gbk', header=None, names=['班级', '姓名', '语文', '数学', '英语', '物理', '化学', '生物'])
print(df)

   班级   姓名   语文   数学     英语  物理   化学   生物
0  班级   姓名   语文   数学     英语  物理   化学   生物
1   1  贾婧瑜  109  126   81.5  55   93   96
2   1  李东泽  118  113   51.0  63   96   98
3   1  王子涵  105   73   51.0  61   99  100
4   1  张乘瑞   88  107   38.0  57  100   91
5   1  任玉莹  103   86   75.0  46   89   85
6   1  张子辰  108   64  100.5  36   86   81

In [13]:
# 运费计算
df = pd.read_excel("运费计算.xlsx")
df['运费'] = df['首重价格'] + np.ceil(df['重量'] - 1) * df['续重价格']
df

           日期            单号  目的地     重量  首重价格  续重价格     运费
0  2020-09-07  732111223456   上海   1.28    15    10   25.0
1  2020-09-08  732111223457  江苏省   0.23    12     9   12.0
2  2020-09-09  732111223458  江苏省   0.69    12     9   12.0
3  2020-09-10  732111223459  江苏省   8.76    12     9   84.0
4  2020-09-11  732111223460  浙江省  15.31    13    10  163.0
5  2020-09-12  732111223461  江苏省   3.82    12     9   39.0
6  2020-09-13  732111223462   上海  17.38    15    10  185.0
7  2020-09-14  732111223463   上海  18.41    15    10  195.0
8  2020-09-15  732111223464  安徽省   7.02    13    11   90.0
9  2020-09-16  732111223465  河北省   2.31    10     8   26.0
10 2020-09-17  732111223466  浙江省  18.85    13    10  193.0
11 2020-09-18  732111223467  江苏省   2.96    12     9   30.0
12 2020-09-19  732111223468  浙江省   2.26    13    10   33.0
13 2020-09-20  732111223469   上海  28.69    15    10  295.0
14 2020-09-21  732111223470  浙江省  29.29    13    10  303.0
15 2020-09-22  732111223471  浙江省   3.70    13    10   43.0
16 2020-09-23  732111223472  浙江省   3.24    13    10   43.0
17 2020-09-24  732111223473  江苏省   5.06    12     9   57.0
18 2020-09-25  732111223474   上海   5.71    15    10   65.0
19 2020-09-26  732111223475  安徽省   6.60    13    11   79.0
20 2020-09-27  732111223476  江苏省  14.51    12     9  138.0
21 2020-09-28  732111223477  浙江省   0.21    13    10   13.0
22 2020-09-29  732111223478   上海   1.24    15    10   25.0
23 2020-09-30  732111223479  海南省   0.60    20    18   20.0

In [17]:
# 筛选动物
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [18]:
# 取出索引为[3, 4, 8]行的animal和age列
df.iloc[[3, 4, 8], [0, 1]]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [19]:
# 计算不同种类动物的平均年龄
df.groupby('animal')['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

In [20]:
df = pd.read_excel('scores.xlsx')
df['总成绩'] = df[['语文', '数学', '英语', '物理', '化学', '生物']].sum(axis=1)
df

    班级    姓名         学号   语文   数学    英语  物理   化学   生物    总成绩
0    1   贾婧瑜  202460101  109  126  81.5  55   93   96  560.5
1    1   李东泽  202460102  118  113  51.0  63   96   98  539.0
2    1   王子涵  202460104  105   73  51.0  61   99  100  489.0
3    1   张乘瑞  202460111   88  107  38.0  57  100   91  481.0
4    1   任玉莹  202460106  103   86  75.0  46   89   85  484.0
..  ..   ...        ...  ...  ...   ...  ..  ...  ...    ...
72   3   黄琬婷  202440217   87   34  40.5  33   58   42  294.5
73   3   宋鑫淼  202440313   88   20  33.0  16   48   56  261.0
74   3   杨皓鑫  202440307   69   34  37.5  14   48   58  260.5
75   3   刘昌林  202440318   15   19  42.0  10   58   41  185.0
76   3  董吴议泽  202440317    0    0  27.0   0   30   48  105.0

[77 rows x 10 columns]

In [27]:
df = pd.read_excel('scores.xlsx')
df = df.replace(0, np.nan)
average = df.groupby('班级')[['语文', '数学', '英语', '物理', '化学', '生物']].mean()
print(average)

           语文         数学         英语         物理         化学         生物
班级
1   98.259259  66.285714  55.785714  37.678571  83.178571  81.357143
2   82.714286  39.892857  43.851852  25.500000  65.851852  72.592593
3   76.842105  50.578947  47.725000  25.842105  58.650000  66.050000

In [26]:
df.replace(0, np.nan)
df

    班级    姓名         学号     语文     数学    英语    物理     化学     生物
0    1   贾婧瑜  202460101  109.0  126.0  81.5  55.0   93.0   96.0
1    1   李东泽  202460102  118.0  113.0  51.0  63.0   96.0   98.0
2    1   王子涵  202460104  105.0   73.0  51.0  61.0   99.0  100.0
3    1   张乘瑞  202460111   88.0  107.0  38.0  57.0  100.0   91.0
4    1   任玉莹  202460106  103.0   86.0  75.0  46.0   89.0   85.0
..  ..   ...        ...    ...    ...   ...   ...    ...    ...
72   3   黄琬婷  202440217   87.0   34.0  40.5  33.0   58.0   42.0
73   3   宋鑫淼  202440313   88.0   20.0  33.0  16.0   48.0   56.0
74   3   杨皓鑫  202440307   69.0   34.0  37.5  14.0   48.0   58.0
75   3   刘昌林  202440318   15.0   19.0  42.0  10.0   58.0   41.0
76   3  董吴议泽  202440317    NaN    NaN  27.0   NaN   30.0   48.0

[77 rows x 9 columns]

In [19]:
df = pd.read_excel('drug_order_detail.xlsx')
df['销售额'] = df['销量'] * df['价格']
df

df.pivot_table(index='分店', values='销售额', aggfunc=['min', 'max', 'mean'])
df.groupby('分店')['销售额'].agg(['min', 'max', 'mean'])

       min    max         mean
分店
人大分店   175  19500  3351.375000
四季青分店  280   5700  1875.666667
花园桥分店   30  19500  2660.111111
金源分店   280   5700  1192.888889